spring:
  application:
    name: bank-system

  datasource:
    url: jdbc:postgresql://localhost:5433/bank
    username: postgres
    password: postgres

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true